## This program detects whether an email is spam or not (1->True and 0->False)

In [31]:
import numpy as np
import pandas as pd
import nltk
from nltk.corpus import stopwords
import string

In [33]:
url="https://raw.githubusercontent.com/amankharwal/Email-spam-detection/master/emails.csv"
df=pd.read_csv(url)

In [35]:
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5728 rows x 2 columns]

In [36]:
#Check for duplicates and remove them
df.drop_duplicates(inplace=True)

In [37]:
df.shape

(5695, 2)

In [38]:
def process_text(text) :
    #1 remove punctuation
    #2 remove stopwords
    #3 return a list of clean words
    
    
    #1
    npnc=[char for char in text if char not in string.punctuation]
    npnc=''.join(npnc)
    #2
    cln_wrds=[word for word in npnc.split() if word.lower not in stopwords.words('english')]
    
    return cln_wrds

In [39]:
# Show the tokenization 
df['text'].head().apply(process_text)

0    [Subject, naturally, irresistible, your, corpo...
1    [Subject, the, stock, trading, gunslinger, fan...
2    [Subject, unbelievable, new, homes, made, easy...
3    [Subject, 4, color, printing, special, request...
4    [Subject, do, not, have, money, get, software,...
Name: text, dtype: object

In [40]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\gulatis\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [41]:
# Now the useless data has been filtered out 
# Convert the text into a matrix of token counts
from sklearn.feature_extraction.text import CountVectorizer


In [42]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(messages_bow, df['spam'], test_size = 0.20, random_state = 0)

In [43]:
messages_bow.shape

(5695, 37380)

In [44]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train, y_train)

MultinomialNB()

In [57]:
## Print the predictions
pred = classifier.predict(X_train)
print(pred)

[0 0 0 ... 0 0 0]


In [54]:
print(y_train.values)

[0 0 0 ... 0 0 0]


In [55]:
#Evaluate the model on the training data set
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score

In [58]:
print(classification_report(y_train ,pred ))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00      3457
           1       0.98      1.00      0.99      1099

    accuracy                           1.00      4556
   macro avg       0.99      1.00      0.99      4556
weighted avg       1.00      1.00      1.00      4556



In [59]:
# Print the values of confusion and accuracy matrix
print('Confusion Matrix: \n',confusion_matrix(y_train,pred))
print()
print('Accuracy: ', accuracy_score(y_train,pred))

Confusion Matrix: 
 [[3439   18]
 [   1 1098]]

Accuracy:  0.9958296751536435


In [60]:
# Looks like that the model is 99.7 % accurate
#Print the predictions
print('Predicted value: ',classifier.predict(X_test))
#Print Actual Label
print('Actual value: ',y_test.values)

Predicted value:  [1 0 0 ... 0 0 0]
Actual value:  [1 0 0 ... 0 0 0]


In [61]:
#Evaluate the model on the test data set
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score
pred = classifier.predict(X_test)
print(classification_report(y_test ,pred ))
print('Confusion Matrix: \n', confusion_matrix(y_test,pred))
print()
print('Accuracy: ', accuracy_score(y_test,pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       870
           1       0.97      0.99      0.98       269

    accuracy                           0.99      1139
   macro avg       0.99      0.99      0.99      1139
weighted avg       0.99      0.99      0.99      1139

Confusion Matrix: 
 [[863   7]
 [  2 267]]

Accuracy:  0.9920983318700615
